name: Github Actions Demo
on: [push]
jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
      - run: ls
      - run: curl https://www.google.com
      

