name: Github Actions Demo
on: [push]
jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "echo"
        run: echo "Hello, world!"
      - name: "ls -al"
        run: ls
      - name: "curl"  
        run: curl https://www.google.com


