name: Github Actions Demo for Unit Test
on: [pull_request, workflow_dispatch]
jobs:
  echo_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ls
        run: ls -al



