name: Github Actions Demo for Unit Test
on: [pull_request, workflow_dispatch]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ls
        run: ls -al
      - name: CheckDefaultNodejs
        run: node --version
      - name: SetupNodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name:  CheckCurrentNodejs
        run: node --version
      - name: InstallDependecies
        run: npm install
      



